WIP feature: set up initial application
meeteor-13/authorization pull request #1
Opened 2019-04-23 20:05 UTC by solairerove

- init schema
- create default migration changelog
- application do nothing

2019-04-25 08:45 UTC, alebabai requested changes

2019-04-25 08:45 UTC, alebabai commented on devtools/docker-compose.yml
> +version: "3"
Мне кажется лучше положить компоуз в рута, добавив туда ещё и саму апликуху.

2019-04-25 08:45 UTC, alebabai commented on devtools/docker-compose.yml
> +version: "3"
И добавить Dockerfile для апликухи.
(скопай у меня)

2019-04-25 08:45 UTC, alebabai commented on devtools/init/postgres/init-schema-postgres.sql
> +CREATE ROLE authorization_user WITH LOGIN PASSWORD 'authorization_pass' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
А зачем это ручками создаём, мб заюзаем дефолтное(схему, юзера(через энвы, sql в sh скрипт) ), контейнер же, наш?

2019-04-25 08:45 UTC, alebabai commented on devtools/init/postgres/init-schema-postgres.sql
> +CREATE ROLE authorization_user WITH LOGIN PASSWORD 'authorization_pass' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
![image](https://user-images.githubusercontent.com/19958900/56721445-90250a00-674d-11e9-9c50-223e28f92c91.png)
типа того

2019-04-25 08:45 UTC, alebabai commented on devtools/data.sql
> +INSERT INTO "authorization".oauth_client_details(client_id,
Зачем нам стабовые данные?
И если они нужно можно бы их в миграцию с дев профайлом (тип дополнительный ченжсет для дева).

2019-04-25 08:45 UTC, alebabai commented on devtools/docker-compose.yml
> +version: "3"
Версия компоуза 3.7 (фиксируем)

2019-04-25 08:45 UTC, alebabai commented on devtools/docker-compose.yml
> +networks:
Мб. лучше будет что-то абстрактное
```
networks:
  internal:
    driver: bridge
```

2019-04-25 08:45 UTC, alebabai commented on devtools/setup-env.sh
> +# PostgreSQL
Это лучше сразу в компоуз добавить в энвы.
Чтоб не через sh запускать

2019-04-25 19:40 UTC, solairerove commented on devtools/data.sql
> +INSERT INTO "authorization".oauth_client_details(client_id,
просто тестовые данные

2019-04-25 19:41 UTC, solairerove commented on devtools/setup-env.sh
> +# PostgreSQL
як

2019-04-25 19:42 UTC, solairerove commented on devtools/init/postgres/init-schema-postgres.sql
> +CREATE ROLE authorization_user WITH LOGIN PASSWORD 'authorization_pass' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
ну тип для каждого сервиса своя схема и юзер. шоб не рутовский тип.
не понимать как делать. открой пулл реквест)

2019-04-25 20:04 UTC, solairerove commented on devtools/docker-compose.yml
> +version: "3"
зафиксировал

2019-04-25 20:04 UTC, solairerove commented on devtools/docker-compose.yml
> +networks:
добавил

2019-04-25 20:04 UTC, solairerove commented on devtools/docker-compose.yml
> +version: "3"
добавил докер файл и перенес композ в рут
есть пару вопросов на обсуждение

2019-04-26 08:42 UTC, alebabai commented on devtools/setup-env.sh
> +# PostgreSQL
```yaml
  db:
    container_name: db
    image: "postgres:latest"
    environment:
     - POSTGRES_USER=meeteor13-auth
     - POSTGRES_PASSWORD=meeteor13-auth
     - POSTGRES_DB=meeteor13-auth
    ports:
     - "5432:5432"
    networks:
      - internal
```

2019-04-26 08:43 UTC, alebabai commented on devtools/data.sql
> +INSERT INTO "authorization".oauth_client_details(client_id,
мб, тогда в тесты

2019-04-26 08:45 UTC, alebabai commented on devtools/init/postgres/init-schema-postgres.sql
> +CREATE ROLE authorization_user WITH LOGIN PASSWORD 'authorization_pass' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
Так нет проблем, что рутовский.
Потому что для каждого сервиса свой инстанс c DB.
![image](https://user-images.githubusercontent.com/19958900/56795274-cbd8d600-6818-11e9-9474-c779a64fc50f.png)

2019-04-26 08:49 UTC, alebabai commented on devtools/init/postgres/init-schema-postgres.sql
> +CREATE ROLE authorization_user WITH LOGIN PASSWORD 'authorization_pass' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
А, кстати, шоб в скриптах не хардкодать базу, юзера и т.д. необязательно через sh, слон и так прокидывает
https://www.postgresql.org/docs/11/functions-info.html

2019-04-26 08:50 UTC, MickevichYura submitted a review, later dismissed

2019-04-26 11:41 UTC, alebabai requested changes

2019-04-26 11:41 UTC, alebabai commented on pom.xml
> +        <dependency>
Please, follow official docs 
https://projectlombok.org/setup/maven

2019-04-26 11:41 UTC, alebabai commented on pom.xml
> +                        <path>
Please, follow official docs

2019-04-26 11:49 UTC, alebabai commented on src/main/java/com/github/meeteor13/authorization/domain/configuration/JpaConfiguration.java
> +public class JpaConfiguration {
Configuration isn't domain.
Please move it to `config` package

2019-04-26 11:52 UTC, alebabai commented on pom.xml
> +        <dependency>
Отпиши плизз, зачем ант переопределён

2019-04-26 12:02 UTC, alebabai commented on src/main/java/com/github/meeteor13/authorization/AuthorizationApplication.java
> +public class AuthorizationApplication {
Maybe use just `Application`

2019-04-26 12:56 UTC, alebabai commented on src/main/resources/application.yaml
> +datasource:
Please, remove this.
Pass props directly to spring props

2019-04-26 12:59 UTC, alebabai requested changes

2019-04-26 12:59 UTC, alebabai commented on src/main/resources/application.yaml
> +  datasource:
Зайюзай всё через конекшн url
Пример
```
jdbc:postgresql://localhost:5432/linden-honey?user=linden-honey&password=linden-honey
```

2019-04-26 12:59 UTC, alebabai commented on src/main/resources/application.yaml
> +  liquibase:
Не стоит переопределять
spring.liquibase.url= # JDBC URL of the database to migrate. If not set, the primary configured data source is used.

2019-04-26 13:05 UTC, alebabai commented
And very important thing
`.yml` instead of `.yaml`

2019-04-26 13:14 UTC, alebabai commented on docker-compose.yml
> +    image: postgres:9.5-alpine
Please, use pg 11.2

2019-04-26 13:16 UTC, alebabai commented on docker-compose.yml
> +#      - 8090:8090
Можешь юзать портмапинг 8080:80 тут.
Я потом создам реп, который всё запускает, там будем компоуз с оверрайдом.

2019-04-26 13:18 UTC, alebabai commented on Dockerfile
> +ENV SERVER_PORT=8090 \
use 80 here

2019-04-26 13:26 UTC, alebabai commented on docker-compose.yml
> +      - "5432:5432"
Заюзай 5433:5432 тут и в application.yml, чтобы была возможность поднять только базы для серверлесс мода.

2019-04-27 10:31 UTC, solairerove commented on src/main/java/com/github/meeteor13/authorization/AuthorizationApplication.java
> +public class AuthorizationApplication {
why

2019-04-27 10:50 UTC, solairerove commented on devtools/data.sql
> +INSERT INTO "authorization".oauth_client_details(client_id,
когда доберусь до тестов тогда

2019-04-27 11:05 UTC, solairerove commented on docker-compose.yml
> +      - "5432:5432"
поменял

2019-04-27 11:05 UTC, solairerove commented on Dockerfile
> +ENV SERVER_PORT=8090 \
ага

2019-04-27 11:05 UTC, solairerove commented on docker-compose.yml
> +#      - 8090:8090
поменял

2019-04-27 11:05 UTC, solairerove commented on docker-compose.yml
> +    image: postgres:9.5-alpine
обновил

2019-04-27 11:06 UTC, solairerove commented on src/main/resources/application.yaml
> +  liquibase:
не переопределил

2019-04-27 11:06 UTC, solairerove commented on src/main/resources/application.yaml
> +  datasource:
зробил

2019-04-27 11:06 UTC, solairerove commented on src/main/resources/application.yaml
> +datasource:
согласен, сделал

2019-04-27 11:06 UTC, solairerove commented on src/main/java/com/github/meeteor13/authorization/AuthorizationApplication.java
> +public class AuthorizationApplication {
если лошадь сдохла, слезь с нее

2019-04-27 11:06 UTC, solairerove commented on pom.xml
> +        <dependency>
отписал

2019-04-27 11:06 UTC, solairerove commented on src/main/java/com/github/meeteor13/authorization/domain/configuration/JpaConfiguration.java
> +public class JpaConfiguration {
мувнул

2019-04-27 11:07 UTC, solairerove commented on pom.xml
> +        <dependency>
сделал провайдед скоуп

2019-04-27 11:07 UTC, solairerove commented on devtools/setup-env.sh
> +# PostgreSQL
сделал

2019-04-27 11:07 UTC, solairerove commented on devtools/init/postgres/init-schema-postgres.sql
> +CREATE ROLE authorization_user WITH LOGIN PASSWORD 'authorization_pass' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
работает - не трожь

2019-04-27 11:08 UTC, solairerove commented
@alebabai чекни и зарезолви дискашены, которые считаешь нужным

2019-04-27 11:14 UTC, alebabai commented on src/main/java/com/github/meeteor13/authorization/AuthorizationApplication.java
> +public class AuthorizationApplication {
> why
типа не указываешь имя продукта в имени класса, максимум пакеты (их проще переименовывать). Сам продукт максимально абстрактен (Application, service, repo)

2019-04-28 14:45 UTC, solairerove commented on src/main/java/com/github/meeteor13/authorization/AuthorizationApplication.java
> +public class AuthorizationApplication {
готовченко

2019-04-28 14:52 UTC, MickevichYura approved these changes

2019-04-29 17:24 UTC, solairerove commented
@alebabai @vadim-hleif чего ждем, товарищи

2019-04-30 08:41 UTC, alebabai approved these changes

2019-04-30 20:12 UTC, merged