feature: migrate to keycloak solution
meeteor-13/authorization pull request #3
Opened 2019-05-13 17:27 UTC by solairerove

2019-05-27 12:09 UTC, alebabai commented
чё там, смигрируем?)

2019-05-27 14:19 UTC, solairerove commented
@alebabai четы хош

2019-05-27 14:25 UTC, alebabai commented
@solairerove oauth 2.0

2019-06-12 12:27 UTC, alebabai commented
Please, change default user&password to `meeteor13`

2019-06-12 12:29 UTC, alebabai commented
Please, test ability to load default config from file (as docker volume) and if it works add config to repository.

2019-06-12 13:29 UTC, solairerove commented
@alebabai и что в этом конфиге должно быть

2019-06-12 13:49 UTC, alebabai commented
@solairerove без понятия, просто иметь возможность (тех же юзеров прописать потом)

2019-08-19 10:20 UTC, alebabai requested changes
Please, change service name to authorization (if it plays that role)
Please, change default port (internal) to 80 - configure keycloak to start on 80 port and update compose mappings .

2019-08-19 17:53 UTC, vadim-gleyf submitted a review, later dismissed

2019-08-20 07:05 UTC, MickevichYura submitted a review, later dismissed

2019-08-21 21:29 UTC, alebabai requested changes
Please, add some pre-defined data for local dev

2019-08-21 22:01 UTC, alebabai requested changes
Please, make /actuator/* endpoints open without token

2019-08-21 22:05 UTC, alebabai commented
TODO:
Configure reverse proxy for keycloak

Something like that
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index c5d73f0..9177e86 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -8,6 +8,7 @@ services:
       POSTGRES_USER: meeteor13
       POSTGRES_PASSWORD: meeteor13
       POSTGRES_DB: meeteor13
+    restart: on-failure
     ports:
       - 5433:5432
     networks:
@@ -30,12 +31,26 @@ services:
       DB_PASSWORD: meeteor13
       KEYCLOAK_USER: meeteor13
       KEYCLOAK_PASSWORD: meeteor13
+      KEYCLOAK_HOSTNAME: authorization
       PROXY_ADDRESS_FORWARDING: "true"
+    restart: on-failure
     ports:
-      - 8081:8080
+      - 8080
     networks:
       - internal

+  authorization_proxy:
+    container_name: authorization_proxy
+    image: nginx:1.17.3-alpine
+    restart: on-failure
+    volumes:
+      - ./nginx.conf:/etc/nginx/nginx.conf:ro
+    ports:
+      - "8081:80"
+    networks:
+      - internal
+
+
 volumes:
   authorization_db:
```

```nginx
user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  text/html;

    server {
        listen 80;

        location / {
            proxy_pass          http://authorization:8080;
            proxy_set_header    Host               $host;
            proxy_set_header    X-Real-IP          $remote_addr;
            proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Host   $host;
            proxy_set_header    X-Forwarded-Server $host;
            proxy_set_header    X-Forwarded-Port   $server_port;
            proxy_set_header    X-Forwarded-Proto  $scheme;
        }
    }
}
```

2019-08-26 14:25 UTC, alebabai approved these changes

2019-08-27 13:07 UTC, vadim-gleyf approved these changes

2019-08-27 13:34 UTC, MickevichYura approved these changes

2019-08-27 15:00 UTC, merged